name: wtd
description: What to do (WTD) is a todo app to save your daily task

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-362.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  fonts:
    - family: MYRIADPRO
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.Otf